import mysql from 'mysql2/promise';
import * as dotenv from 'dotenv';
dotenv.config();

const conn = await mysql.createConnection(process.env.DATABASE_URL);

// Topics
await conn.execute(`INSERT IGNORE INTO topics (id, label, labelEn, \`desc\`, color, sortOrder) VALUES
  ('data-privacy', '数据与隐私治理', 'Data & Privacy', '个人信息保护、数据跨境流动、隐私权利保障', 'oklch(46% 0.2 245)', 1),
  ('ai', '人工智能治理', 'AI Governance', '算法规制、生成式AI监管、自动化决策问责', 'oklch(50% 0.2 290)', 2),
  ('antitrust', '垄断与不正当竞争', 'Antitrust', '平台垄断、并购审查、数据垄断执法', 'oklch(54% 0.18 55)', 3),
  ('content', '内容治理', 'Content Governance', '违法内容、平台责任、信息操控与虚假信息', 'oklch(48% 0.18 162)', 4),
  ('other', '其他', 'Other', '其他平台治理相关议题', 'oklch(50% 0.1 0)', 5)
`);

// Jurisdictions
await conn.execute(`INSERT IGNORE INTO jurisdictions (id, label, labelEn, flag, color, sortOrder) VALUES
  ('cn', '中国', 'China', '🇨🇳', 'oklch(48% 0.18 25)', 1),
  ('eu', '欧盟', 'European Union', '🇪🇺', 'oklch(46% 0.2 245)', 2),
  ('us', '美国', 'United States', '🇺🇸', 'oklch(54% 0.18 55)', 3),
  ('sea', '东南亚', 'Southeast Asia', '🌏', 'oklch(48% 0.18 162)', 4),
  ('other', '其他', 'Other', '🌐', 'oklch(50% 0.1 0)', 5)
`);

// Cases data
const cases = [
  ['legislation', '欧盟《人工智能法》', 'EU Artificial Intelligence Act', 'ai', 'eu', '2024-08-01', 'European Parliament & Council', 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689', 'The EU AI Act is the first comprehensive legal framework on AI, establishing a risk-based regulatory approach.', '《欧盟人工智能法》是全球首部综合性人工智能法律框架，于2024年8月正式生效。该法案采用风险分级监管方式，将AI系统分为不可接受风险（禁止）、高风险（严格合规要求）、有限风险（透明度义务）和最低风险（自愿行为准则）四个等级。对高风险AI系统，企业须进行合规评估、建立风险管理体系、保存技术文档，并向欧盟AI数据库登记。', '从监管框架角度来看，《欧盟人工智能法》开创了以风险为基础的人工智能治理范式，与GDPR共同构成欧盟数字监管体系的核心支柱。该法案对全球AI治理具有"布鲁塞尔效应"：非欧盟企业若向欧盟用户提供AI系统，同样受该法约束。对于中国平台企业出海欧盟，合规成本和技术准入壁垒将显著提升。', JSON.stringify(['人工智能','AI治理','欧盟','风险分级','生成式AI']), 'en', 'published', 1243],
  ['regulatory', 'Meta因违反GDPR被爱尔兰DPC罚款12亿欧元', 'Meta fined 1.2B by Irish DPC for GDPR Violation', 'data-privacy', 'eu', '2023-05-22', '爱尔兰数据保护委员会 (DPC)', 'https://www.dataprotection.ie', 'The Irish DPC fined Meta 1.2 billion euros for transferring EU user data to the US without adequate safeguards.', '2023年5月，爱尔兰数据保护委员会（DPC）对Meta爱尔兰公司开出12亿欧元罚款，创下GDPR实施以来最大罚款记录。违规事由为Meta将欧盟/欧洲经济区Facebook用户个人数据转移至美国，违反了GDPR第46条关于数据跨境传输的规定。', '本案的核心争议在于EU-US数据传输框架的合法性问题。自2020年"Schrems II"判决废止"隐私盾"协议后，跨大西洋数据传输面临重大法律不确定性。12亿欧元的天价罚款具有强烈的威慑信号意义，预示欧盟将对科技巨头数据跨境传输行为保持高压监管态势。', JSON.stringify(['GDPR','Meta','数据跨境传输','隐私保护','欧盟']), 'en', 'published', 2187],
  ['judicial', '腾讯音乐娱乐集团独家版权垄断案', 'Tencent Music Exclusive Copyright Antitrust Case', 'antitrust', 'cn', '2021-07-24', '国家市场监督管理总局', 'http://www.samr.gov.cn', '国家市场监督管理总局责令腾讯解除独家版权协议，限期剥离相关业务，并处以50万元罚款。', '2021年7月，国家市场监督管理总局对腾讯控股旗下腾讯音乐娱乐集团作出处罚，责令其解除与索尼、华纳、环球等主要唱片公司签订的独家版权协议，并在30天内向竞争对手转授相关版权。', '本案是中国数字音乐平台反垄断执法的标志性案例，深刻影响了中国平台经济反垄断执法的走向。腾讯以独家版权为核心构建的竞争壁垒被强制打破，与2021年阿里巴巴被罚182亿元案共同标志着中国互联网平台反垄断"强监管时代"的到来。', JSON.stringify(['反垄断','腾讯','音乐版权','独家协议','中国']), 'zh', 'published', 1876],
  ['legislation', '中华人民共和国个人信息保护法', 'Personal Information Protection Law of the PRC', 'data-privacy', 'cn', '2021-11-01', '全国人民代表大会常务委员会', 'http://www.npc.gov.cn', '《个人信息保护法》是中国首部专门保护个人信息的综合性法律，于2021年11月1日正式施行。', '《个人信息保护法》（PIPL）是中国数据保护领域的里程碑立法，核心内容包括：确立"告知—同意"为个人信息处理的基本合法性基础；赋予个人知情权、决定权、查阅权、复制权、更正权、删除权等权利；规定敏感个人信息须单独同意；设定个人信息跨境提供的安全评估、认证和标准合同三种合规路径。', 'PIPL与GDPR在结构框架上有诸多相似之处，但具有鲜明的中国特色：一是将国家安全例外条款纳入法律；二是对"重要数据"概念与《数据安全法》相衔接；三是对境外实体涉华个人信息处理的域外管辖权。', JSON.stringify(['个人信息保护','PIPL','数据合规','中国','隐私权']), 'zh', 'published', 3421],
  ['judicial', 'FTC诉Meta垄断案（Instagram & WhatsApp并购审查）', 'FTC v. Meta Platforms (Antitrust)', 'antitrust', 'us', '2021-08-19', '美国联邦贸易委员会 (FTC)', 'https://www.ftc.gov', 'The FTC filed an amended complaint against Meta alleging illegal monopoly maintenance through acquisitions of Instagram and WhatsApp.', '美国联邦贸易委员会（FTC）于2020年12月对Facebook提起反垄断诉讼，指控其通过收购Instagram（2012年）和WhatsApp（2014年）非法维持个人社交网络市场垄断地位。2021年8月提交修订诉状，提供了更为详尽的市场份额和垄断行为证据。', '本案代表了美国互联网平台反垄断执法的新方向，即对平台历史收购行为进行追溯审查。这种"事后追责"模式对平台并购策略产生深远影响，也引发了学界对法律确定性的讨论。', JSON.stringify(['反垄断','Meta','FTC','并购审查','美国']), 'en', 'published', 2654],
  ['legislation', '欧盟《数字服务法》(DSA)', 'EU Digital Services Act', 'content', 'eu', '2023-02-17', '欧盟委员会', 'https://digital-strategy.ec.europa.eu/en/policies/digital-services-act-package', 'The DSA creates a safer online environment by establishing obligations for digital services and special rules for Very Large Online Platforms.', '《数字服务法》（DSA）于2023年2月正式对超大型在线平台生效，是欧盟针对数字平台内容治理的核心立法。DSA确立了平台对非法内容的"通知与行动"机制，禁止基于敏感特征的定向广告，要求算法系统透明度。', 'DSA的实施标志着欧盟从被动内容监管转向主动平台问责的范式转变。特别值得关注的是，DSA对TikTok等中国企业的欧盟业务产生直接约束——欧盟委员会已就TikTok算法和儿童保护问题启动正式调查。', JSON.stringify(['数字服务法','DSA','内容治理','平台责任','欧盟']), 'en', 'published', 1932],
  ['legislation', '印度尼西亚《个人数据保护法》(UU PDP)', 'Indonesia Personal Data Protection Law', 'data-privacy', 'sea', '2022-10-17', '印度尼西亚政府', 'https://jdih.kominfo.go.id', 'Indonesia enacted its first comprehensive Personal Data Protection Law in October 2022.', '印度尼西亚于2022年10月通过首部综合性个人数据保护法（UU PDP），标志着东南亚最大经济体正式建立个人数据保护制度。该法在很大程度上参考了欧盟GDPR框架，核心内容包括数据主体的知情权、访问权、更正权、删除权等。', '印尼PDP法的出台是东南亚数据保护立法浪潮的重要组成部分，与泰国PDPA、新加坡PDPA修订等共同构成东南亚数字治理法律体系。对于在东南亚布局的中国互联网企业，需重点关注各国数据本地化要求差异。', JSON.stringify(['东南亚','印度尼西亚','数据保护','GDPR参考']), 'en', 'published', 876],
  ['judicial', '美国诉谷歌搜索垄断案', 'United States v. Google LLC (Search Monopoly)', 'antitrust', 'us', '2024-08-05', '美国联邦地区法院（D.D.C.）', 'https://www.justice.gov/atr/us-v-google-llc-2023', 'US District Judge ruled that Google illegally maintained a monopoly in the general search engine market.', '2024年8月，美国联邦地区法院法官Amit Mehta裁定谷歌违反《谢尔曼法》第二条，非法维持其在通用搜索市场的垄断地位。法院认定，谷歌每年向苹果等设备制造商支付约260亿美元，换取成为默认搜索引擎，构成排他性分销协议。', '本案是继2001年微软反垄断案后美国科技行业最重要的反垄断司法判决。裁决确认了"默认地位"付费行为的违法性，对科技平台的分销和捆绑策略产生深远影响。', JSON.stringify(['谷歌','搜索垄断','美国司法部','反垄断','默认协议']), 'en', 'published', 4231],
  ['legislation', '中华人民共和国数据安全法', 'Data Security Law of the PRC', 'data-privacy', 'cn', '2021-09-01', '全国人民代表大会常务委员会', 'http://www.npc.gov.cn', '《数据安全法》建立了中国数据分类分级保护制度，将数据安全纳入国家安全体系。', '《数据安全法》于2021年9月1日施行，与《个人信息保护法》《网络安全法》共同构成中国数据法律体系的"三驾马车"。该法确立数据分类分级制度，将数据分为一般数据、重要数据和核心数据，对核心数据设定最严格的保护要求。', '《数据安全法》的重要特征在于其将数据安全与国家安全紧密相连，赋予了政府宽泛的数据访问权力，同时对数据跨境流动设置了严格限制。对跨国企业而言，中美数据法律体系的冲突是最棘手的合规挑战之一。', JSON.stringify(['数据安全','国家安全','数据分类','中国','数据主权']), 'zh', 'published', 2876],
  ['regulatory', '欧盟委员会对TikTok发起DSA正式调查', 'EC Opens Formal DSA Proceedings Against TikTok', 'content', 'eu', '2024-02-19', '欧盟委员会', 'https://commission.europa.eu', 'The European Commission opened formal proceedings against TikTok under the DSA to assess potential breaches.', '欧盟委员会于2024年2月依据《数字服务法》（DSA）对TikTok启动正式调查，重点审查四个方面：未成年人保护机制、算法推荐系统透明度、对外部研究人员的数据访问保障，以及平台设计的成瘾性机制风险管理。', '本案是DSA实施后欧盟委员会对中国平台发起的首例正式调查，具有重要的信号意义。TikTok月活用户超1.7亿，承担最严格的合规义务。调查结果将深刻影响TikTok的欧盟业务模式，并可能成为欧盟监管中国平台的重要先例。', JSON.stringify(['TikTok','DSA','内容治理','未成年人保护','欧盟']), 'en', 'published', 3102],
  ['legislation', '生成式人工智能服务管理暂行办法', 'Interim Measures for the Administration of Generative AI Services', 'ai', 'cn', '2023-08-15', '国家互联网信息办公室等', 'http://www.cac.gov.cn', '全球首部专门针对生成式AI服务的监管规定，规定生成式AI服务提供者须承担训练数据合规、内容安全等义务。', '《生成式人工智能服务管理暂行办法》于2023年8月15日施行，是全球首部专门针对大型语言模型和生成式AI服务的监管规定。核心要求包括：训练数据须合法获取；生成内容须符合社会主义核心价值观；向公众提供服务须向网信部门备案。', '从全球视角看，中国以专项规定形式率先完成生成式AI立法，领先于美国和欧盟。与欧盟《AI法》相比，中国的规定更注重内容安全和意识形态合规，而非算法透明度和基本权利保护。', JSON.stringify(['生成式AI','AIGC','中国','内容安全','LLM']), 'zh', 'published', 2341],
  ['regulatory', '新加坡竞争与消费者委员会对Grab-Uber并购案审查', 'CCCS Review: Grab Acquisition of Uber Southeast Asia', 'antitrust', 'sea', '2018-09-24', '新加坡竞争与消费者委员会 (CCCS)', 'https://www.cccs.gov.sg', "CCCS found that Grab's acquisition of Uber's Southeast Asian operations substantially lessened competition.", '2018年9月，新加坡竞争与消费者委员会（CCCS）就Grab收购Uber东南亚业务作出裁决，认定该合并实质性削弱了新加坡网约车市场竞争，对Grab和Uber各处以超过1300万新元罚款。', '本案是东南亚平台经济反垄断执法的早期重要案例，标志着东南亚监管机构开始对超级平台的扩张行为进行审查。CCCS选择对收购双方均予处罚，体现了监管机构将出售方视为竞争损害共同责任人的态度。', JSON.stringify(['东南亚','新加坡','Grab','Uber','网约车']), 'en', 'published', 654],
  ['legislation', '欧盟《数字市场法》(DMA)', 'EU Digital Markets Act', 'antitrust', 'eu', '2023-05-02', '欧盟委员会', 'https://digital-markets-act.ec.europa.eu', "The DMA regulates 'gatekeepers' — large online platforms with significant market power — imposing ex-ante obligations.", '《数字市场法》（DMA）于2023年5月正式生效，通过设定"守门人"（Gatekeeper）制度对科技巨头进行事前规制。已被认定的守门人包括谷歌、Meta、苹果、亚马逊、微软和字节跳动（TikTok）。', 'DMA与DSA共同构成欧盟"数字一揽子法案"，代表了欧盟从事后反垄断执法向事前行为规制的重大转型。字节跳动作为首家被纳入守门人范畴的中国企业，开创了欧盟数字监管覆盖中国平台的先例。', JSON.stringify(['数字市场法','DMA','守门人','反垄断','欧盟']), 'en', 'published', 1765],
  ['regulatory', '中国国家互联网信息办公室对滴滴出行数据安全处罚案', 'CAC Penalty on Didi Chuxing for Data Security Violations', 'data-privacy', 'cn', '2022-07-21', '国家互联网信息办公室', 'http://www.cac.gov.cn', '国家互联网信息办公室对滴滴全球股份有限公司处以80.26亿元人民币罚款及相关处罚。', '2022年7月，国家互联网信息办公室对滴滴出行处以80.26亿元罚款，是中国迄今最大的数据安全处罚。调查发现滴滴存在16项违法行为，包括：违法收集用户数据、过度收集乘客人脸识别信息、违规使用精准位置信息等。', '滴滴案是中国平台监管与国家数据安全政策深度交织的标志性案例。监管行动触发于赴美上市的时间节点，被解读为监管层对科技企业境外上市可能导致敏感数据暴露的高度警觉。本案深刻影响了中国科技企业的境外上市决策。', JSON.stringify(['滴滴','数据安全','网络安全审查','中国','跨境数据']), 'zh', 'published', 3876],
  ['legislation', '越南《网络安全法》', 'Vietnam Cybersecurity Law', 'data-privacy', 'sea', '2019-01-01', '越南国会', 'https://vanban.chinhphu.vn', "Vietnam's Cybersecurity Law requires enterprises to localize data of Vietnamese users and remove harmful content within 24 hours.", '越南《网络安全法》于2019年1月1日施行，是东南亚较早实施严格数据本地化要求的立法。核心规定包括：为越南用户提供服务的境内外企业须将越南用户数据存储于越南境内服务器；须在24小时内响应政府删除内容请求。', '越南《网络安全法》引发了包括谷歌、Facebook在内的国际科技企业和人权组织的强烈批评，认为数据本地化和内容审查要求侵害言论自由。本法对理解东南亚"数字主权"立法趋势具有重要意义。', JSON.stringify(['越南','东南亚','数据本地化','网络安全','内容审查']), 'en', 'published', 987],
];

for (const c of cases) {
  await conn.execute(
    `INSERT IGNORE INTO \`cases\` (type, title, titleEn, topicId, jurisdictionId, date, source, sourceUrl, abstract, aiSummary, aiAnalysis, tags, language, status, views)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    c
  );
}

// Platforms
const platforms = [
  ['tiktok', 'TikTok / 抖音', '字节跳动 (ByteDance)', JSON.stringify(['cn','us','eu','sea']), 2016, '中国北京', 'oklch(62% 0.2 330)', 'TK', 'TikTok（国内版：抖音）是全球最大的短视频内容平台，由字节跳动于2016年创立。截至2024年，TikTok全球月活跃用户超过15亿，覆盖150余个国家和地区。', JSON.stringify({types:['内容','社交','AIGC'],structure:'双边（创作者 ↔ 观众）',contentSource:'UGC / AI辅助创作',networkEffect:'直接（社交）+ 数据驱动',businessModel:['广告','电商抽佣','直播打赏','订阅'],openness:'半开放（开放平台API / 小程序生态）',crossBorder:'双轨结构（抖音中国版 + TikTok国际版）'}), JSON.stringify([{date:'2024-01',title:'TikTok隐私政策（欧盟/EEA版）',type:'privacy',url:'https://www.tiktok.com/legal/page/eea/privacy-policy/en'},{date:'2023-09',title:'TikTok社区指引 v7.0',type:'governance',url:'https://www.tiktok.com/community-guidelines'}]), JSON.stringify([{date:'2016-09',event:'抖音在中国正式上线'},{date:'2017-05',event:'TikTok国际版上线，覆盖东南亚市场'},{date:'2018-08',event:'收购Musical.ly，完成与TikTok的合并'},{date:'2020-08',event:'特朗普政府签署行政令威胁禁止TikTok'},{date:'2023-03',event:'CEO周受资出席美国国会听证会'},{date:'2024-04',event:'美国《TikTok强制剥离法案》经拜登签署成为法律'},{date:'2025-01',event:'美国最高法院维持剥离法令，TikTok短暂关闭后恢复'}]), JSON.stringify(['6','10']), 1],
  ['meta', 'Meta（Facebook / Instagram / WhatsApp）', 'Meta Platforms, Inc.', JSON.stringify(['us','eu','sea']), 2004, '美国加利福尼亚州门洛帕克', 'oklch(58% 0.22 260)', 'M', 'Meta是全球最大的社交媒体公司，旗下拥有Facebook、Instagram、WhatsApp、Messenger等核心平台，月活跃用户合计超过39亿。', JSON.stringify({types:['社交','内容','即时通讯','AIGC'],structure:'多边（用户、广告主、开发者、内容创作者）',contentSource:'UGC / PGC / 混合',networkEffect:'直接（社交）+ 间接（广告）',businessModel:['广告','订阅（Meta Verified）','元宇宙硬件'],openness:'半开放（Graph API / 开放平台）',crossBorder:'全球统一品牌，部分市场本地化运营'}), JSON.stringify([{date:'2023-12',title:'Meta隐私政策（最新版）',type:'privacy',url:'https://www.facebook.com/privacy/policy'},{date:'2023-11',title:'Facebook社区准则',type:'governance',url:'https://transparency.fb.com/policies/community-standards/'}]), JSON.stringify([{date:'2004-02',event:'Facebook在哈佛大学创立'},{date:'2012-04',event:'以10亿美元收购Instagram'},{date:'2014-02',event:'以190亿美元收购WhatsApp'},{date:'2018-03',event:'剑桥分析数据泄露丑闻曝光'},{date:'2021-10',event:'公司更名为Meta Platforms，宣布元宇宙战略'},{date:'2023-05',event:'爱尔兰DPC开出12亿欧元GDPR史上最大罚款'}]), JSON.stringify(['2','5']), 2],
  ['google', 'Google（搜索 / YouTube / Android）', 'Alphabet Inc.', JSON.stringify(['us','eu','sea']), 1998, '美国加利福尼亚州山景城', 'oklch(68% 0.18 150)', 'G', 'Google是全球最大的搜索引擎和数字广告平台，市场份额长期维持在90%以上。旗下YouTube是全球最大的视频平台，Android系统统治移动操作系统市场。', JSON.stringify({types:['搜索','内容','应用分发','云','AIGC'],structure:'多边（用户、广告主、开发者、内容创作者、企业客户）',contentSource:'UGC（YouTube）/ 索引内容 / OGC',networkEffect:'间接（广告）+ 数据驱动',businessModel:['广告','云服务订阅','应用分发抽佣','硬件'],openness:'半开放（Android开源 / Google Play封闭）',crossBorder:'全球统一平台，部分市场受限（中国）'}), JSON.stringify([{date:'2023-11',title:'Google隐私政策（最新版）',type:'privacy',url:'https://policies.google.com/privacy'},{date:'2023-09',title:'Google Play开发者政策',type:'governance',url:'https://play.google.com/about/developer-content-policy/'}]), JSON.stringify([{date:'1998-09',event:'Google在斯坦福大学创立'},{date:'2004-04',event:'Gmail上线，开启免费大容量邮箱时代'},{date:'2006-10',event:'以16.5亿美元收购YouTube'},{date:'2008-09',event:'Android 1.0发布，开启移动互联网时代'},{date:'2024-08',event:'美国联邦法院裁定谷歌非法垄断搜索市场'}]), JSON.stringify(['8','13']), 3],
  ['alibaba', '阿里巴巴集团', 'Alibaba Group Holding Limited', JSON.stringify(['cn','sea']), 1999, '中国浙江杭州', 'oklch(68% 0.18 55)', 'ALI', '阿里巴巴集团是中国最大的电子商务平台，旗下拥有淘宝、天猫、阿里云、支付宝（蚂蚁集团）等核心业务。2021年因滥用市场支配地位被处以182亿元罚款。', JSON.stringify({types:['电商','云','支付','本地生活'],structure:'多边（消费者、商家、广告主、开发者）',contentSource:'PGC / 商家内容',networkEffect:'间接（电商平台）+ 数据驱动',businessModel:['电商抽佣','广告','云服务','金融科技'],openness:'半开放（阿里云API / 开放平台）',crossBorder:'国内为主，东南亚（Lazada）为主要海外市场'}), JSON.stringify([{date:'2023-09',title:'淘宝平台服务协议',type:'terms',url:'https://terms.alicdn.com/legal-agreement/terms/suit_bu1_taobao/'},{date:'2023-06',title:'阿里巴巴隐私权政策',type:'privacy',url:'https://terms.alicdn.com/legal-agreement/terms/suit_bu1_alibaba/'}]), JSON.stringify([{date:'1999-09',event:'阿里巴巴在杭州创立'},{date:'2003-05',event:'淘宝网上线'},{date:'2004-12',event:'支付宝上线'},{date:'2014-09',event:'纽交所IPO，创当时全球最大IPO记录'},{date:'2021-04',event:'国家市场监管总局开出182亿元反垄断罚款'}]), JSON.stringify(['3']), 4],
  ['apple', 'Apple（App Store / iOS）', 'Apple Inc.', JSON.stringify(['us','eu']), 1976, '美国加利福尼亚州库比蒂诺', 'oklch(55% 0.05 0)', 'AAPL', 'Apple通过iOS生态系统和App Store构建了全球最大的移动应用分发平台之一。App Store的30%抽佣政策和对侧载的限制引发了全球范围内的反垄断调查。', JSON.stringify({types:['应用分发','内容','AIGC'],structure:'双边（开发者 ↔ 用户）',contentSource:'PGC / 开发者内容',networkEffect:'间接（平台效应）',businessModel:['应用分发抽佣','订阅服务（Apple One）','硬件'],openness:'封闭（iOS生态 / App Store独占）',crossBorder:'全球统一平台，部分内容按国家区分'}), JSON.stringify([{date:'2024-03',title:'App Store审核指南（DMA合规版）',type:'governance',url:'https://developer.apple.com/app-store/review/guidelines/'},{date:'2023-09',title:'Apple隐私政策',type:'privacy',url:'https://www.apple.com/legal/privacy/'}]), JSON.stringify([{date:'1976-04',event:'苹果公司创立'},{date:'2008-07',event:'App Store正式上线'},{date:'2020-08',event:'Epic Games起诉苹果App Store垄断'},{date:'2023-03',event:'欧盟DMA认定苹果为守门人'},{date:'2024-03',event:'苹果宣布在欧盟开放第三方应用商店以符合DMA要求'}]), JSON.stringify(['13']), 5],
];

for (const p of platforms) {
  await conn.execute(
    `INSERT IGNORE INTO platforms (id, name, company, jurisdiction, founded, hq, color, abbr, description, portrait, rules, timeline, relatedCaseIds, sortOrder)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    p
  );
}

await conn.end();
console.log('Seed completed successfully!');
